name: Build Wheels

on: 
  push:
    branches:
    - develop
    - feature/*
  pull_request:
    branches:
    - develop

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, macos-latest, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.10'

      - uses: ilammy/msvc-dev-cmd@v1.12.1
        if: runner.os == 'Windows'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Install Windows Build Deps
        if: runner.os == 'Windows'
        run: choco install swig --version=4.1.1 --no-progress -y

      - name: Generate Windows SWIG Files
        if: runner.os == 'Windows'
        run: .\tools\msvc\swig.bat
        env:
          SWIG_PATH: "C:\\ProgramData\\chocolatey\\lib\\swig\\tools\\install\\swigwin-4.1.1"

      - name: Generate ecmult_static_context.h
        if: runner.os == 'Windows'
        run: .\tools\msvc\gen_ecmult_static_context.bat
        env:
          LIBWALLY_DIR: "."

      - name: Install macOS Build Deps
        if: runner.os == 'macOS'
        run: brew install gnu-sed swig automake

      - name: Install Linux Build Deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y swig python3-dev

      - name: Build Wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "cp27-* cp35-* cp36-* cp37-* pp* *-musllinux*"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_WINDOWS: "AMD64"

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl
